--return {
--    -- deno
--    -- An ecosystem for Vim/Neovim enabling developers to write plugins in Deno.
--    --
--    {
--        "vim-denops/denops.vim",
--        dependencies = {
--            { "vim-denops/denops-shared-server.vim", build = ":call denops_shared_server#install()" },
--            { "vim-denops/denops-helloworld.vim" },
--        },
--    },
--
--    --     Dark Power Series
--    {
--        -- https://zenn.dev/vim_jp/articles/20231020step-by-step-ddu
--        "Shougo/ddu.vim",
--        dependencies = {
--            "vim-denops/denops.vim",
--            -- source : Generate an Item list.
--            -- file_recursiveの略です。
--            "Shougo/ddu-source-file_rec",
--            "4513ECHO/ddu-source-colorscheme",
--            -- filter : Receive input from users and process UI
--            "Shougo/ddu-filter-matcher_substring",
--            "uga-rosa/ddu-filter-converter_devicon",
--            -- kind : Define the action to be performed on the Item.
--            "Shougo/ddu-kind-file",
--            -- UI : Display the Item list.
--            -- fuzzy_finder(あいまい検索)
--            "Shougo/ddu-ui-ff",
--        },
--        config = function()
--            vim.fn["ddu#custom#patch_global"]({
--                ui = "ff",
--                -- floating window
--                --                uiParams = {
--                --                    ff = {
--                --                        filterFloatingPosition = "bottom",
--                --                        filterSplitDirection = "floating",
--                --                        floatingBorder = "rounded",
--                --                        previewFloating = true,
--                --                        previewFloatingBorder = "rounded",
--                --                        previewFloatingTitle = "Preview",
--                --                        previewSplit = "horizontal",
--                --                        prompt = "> ",
--                --                        split = "floating",
--                --                        startFilter = true,
--                --                    },
--                --                },
--                sourceOptions = {
--                    _ = {
--                        matchers = {
--                            "matcher_substring",
--                        },
--                        ignoreCase = true,
--                    },
--                },
--            })
--
--            -- :call ddu#start(#{name:"file_recursive"})
--            vim.fn["ddu#custom#patch_local"]("file_recursive", {
--                sources = {
--                    {
--                        name = { "file_rec" },
--                        options = {
--                            converters = {
--                                "converter_devicon",
--                            },
--                        },
--                        params = {
--                            ignoredDirectories = { "node_modules", ".git", ".vscode" },
--                        },
--                    },
--                },
--
--                kindOptions = {
--                    file = {
--                        defaultAction = "open",
--                    },
--                },
--            })
--
--            -- :call ddu#start(#{name:"colorscheme"})
--            vim.fn["ddu#custom#patch_local"]("colorscheme", {
--                sources = {
--                    {
--                        name = { "colorscheme" },
--                    },
--                },
--                kindOptions = {
--                    colorscheme = {
--                        defaultAction = "set",
--                    },
--                },
--            })
--
--            vim.api.nvim_create_autocmd("FileType", {
--                pattern = "ddu-ff",
--                callback = function()
--                    local opts = { noremap = true, silent = true, buffer = true }
--                    vim.keymap.set({ "n" }, "q", [[<Cmd>call ddu#ui#do_action('quit')<CR>]], opts)
--                    vim.keymap.set({ "n" }, "<CR>", [[<Cmd>call ddu#ui#do_action('itemAction')<CR>]], opts)
--                    vim.keymap.set({ "n" }, "i", [[<Cmd>call ddu#ui#do_action('openFilterWindow')<CR>]], opts)
--                    vim.keymap.set({ "n" }, "P", [[<Cmd>call ddu#ui#do_action("togglePreview")<CR>]], opts)
--                end,
--            })
--
--            vim.api.nvim_create_autocmd("FileType", {
--                pattern = "ddu-ff-filter",
--                callback = function()
--                    local opts = { noremap = true, silent = true, buffer = true }
--                    vim.keymap.set({ "n", "i" }, "<CR>", [[<Esc><Cmd>close<CR>]], opts)
--                end,
--            })
--        end,
--    },
--}
